In [8]:
#Ord() nos ayuda a ver cuál es el código ASCII para el string que coloquemos
a=('a', 'b', 'c')
b= ('a','b', 'd')

print(ord('c')) #alt+99 = c
a>b

99


False

In [9]:
#Ord() nos ayuda a ver cuál es el código ASCII para el string que coloquemos
a=['a', 'b', 'c']
b=['a', 'b', 'd']

print(ord('c')) #alt+99 = c
a>b

99


False

In [10]:
#Ord() nos ayuda a ver cuál es el código ASCII para el string que coloquemos
a='a', 'b', 'c'
b=('a', 'b', 'c')
c=('d','e')

print(a == b)
print(a > c)
print(a < c)
print(a + c)
print([a + c])
print(a)

True
False
True
('a', 'b', 'c', 'd', 'e')
[('a', 'b', 'c', 'd', 'e')]
('a', 'b', 'c')


In [23]:
#cuantos días se ha reducido la venta en comparacion con el dia anterior
ventas = (100, 121, 120, 130, 140, 120, 122, 123, 190, 125)

#variable para saber cuantos días se ha reducido
reduccion = 0

for i in range(1, len(ventas)):
    if ventas[i] < ventas[i-1]:
        reduccion += 1
        
print(reduccion) 

3


In [24]:
#variable temporal

a = 100
b = 200

print(f'variables antes de la cambiar con temp a = {a}, b = {b}')
temp = a
a = b
b = temp

print(f'variables después de la cambiar con temp a = {a}, b = {b}')

variables antes de la cambiar con temp a = 100, b = 200
variables después de la cambiar con temp a = 200, b = 100


In [25]:
tupla = (3,2,5,4)

temp = list(tupla)

temp.sort()

print(temp)


[2, 3, 4, 5]


In [35]:
#decifrar que numero se remite más veces y cual es mayor
tupla = (1, 2, 5, 4, 3, 2, 1, 4, 7, 8, 9, 9, 3, 7, 3, 9)

#dic para contar las ocurrencias
contador = {}

for i in tupla:
    if i in contador:
        continue
    elif tupla.count(i) > 1:
        contador[i] = tupla.count(i)       
   
numero_comun = None
max_ocurrencias = 0

for numero, veces_repetidas in contador.items():
    if veces_repetidas >= max_ocurrencias:
        numero_comun = numero
        max_ocurrencias = veces_repetidas
        
print(f'{numero_comun} {max_ocurrencias}')
        

9 3


In [3]:
import random

seat = []

for i in range(3):
    line = []
    for j in range(6):
        rand = random.randrange(0,2)
        line.append(rand)
    seat.append(line)
    
avalible = 0 

for i in range(3):
    for j in range(6):
        print(seat[i][j], '', end='')
        if seat[i][j] == 0:
            avalible += 1
    print()
    
print(f'el numero de asinetos restantes es de: {seat}')

1 0 1 0 1 0 
1 1 1 0 0 1 
0 0 0 0 1 0 
el numero de asinetos restantes es de: [[1, 0, 1, 0, 1, 0], [1, 1, 1, 0, 0, 1], [0, 0, 0, 0, 1, 0]]


In [2]:
import numpy as np

def mostrar(matriz):
    print(matriz.shape)
    print(type(matriz))
    print(matriz)
    
mostrar(np.array([[23,12,3]]))



(1, 3)
<class 'numpy.ndarray'>
[[23 12  3]]


In [51]:
import random

seat = []

for i in range(6):
    line = []
    for j in range(6):
        rand = random.randrange(0,2)
        line.append(rand)
    seat.append(line) 

print(seat)

avalible = 0
for i in range(6):
    for j in range(6):
        print(seat[i][j],'',end='')
        if seat[i][j] == 0:
            avalible += 1
    print()

[[0, 0, 0, 1, 0, 0], [0, 0, 1, 0, 0, 1], [1, 0, 1, 0, 1, 1], [1, 0, 1, 0, 0, 1], [0, 0, 0, 1, 1, 0], [0, 0, 1, 0, 0, 0]]
0 0 0 1 0 0 
0 0 1 0 0 1 
1 0 1 0 1 1 
1 0 1 0 0 1 
0 0 0 1 1 0 
0 0 1 0 0 0 


In [52]:
lsit = [[10, 20], [30, 40], [50, 60]]

lsit[1][0]

30

In [29]:
n = int(input('ingresa un numero: '))

matriz = []

for i in range(n):
    fila = []
    for j in range(n):
        if (j + i) % 2 == 0:
            fila.append(1)
        else:
            fila.append(0)
    matriz.append(fila)

for i in range(n):
    for j in range(n):
        print(matriz[i][j],'',end='')
    print()
        

1 0 1 0 1 
0 1 0 1 0 
1 0 1 0 1 
0 1 0 1 0 
1 0 1 0 1 


In [20]:
#whith numpy
import numpy as np

def crear_patron_a_cuadros(n):
    # Crear un arreglo de tamaño nxn con ceros
    arreglo = np.zeros((n, n), dtype=int)
    
    # Llenar el arreglo con el patrón a cuadros
    for i in range(n):
        for j in range(n):
            if (i + j) % 2 == 0:
                arreglo[i, j] = 1
    return arreglo

# Solicitar al usuario dos o más valores de n
valores_n = input("Ingrese dos o más valores de n separados por espacios: ").split()
valores_n = [int(n) for n in valores_n]

# Generar y mostrar los arreglos para cada valor de n
for n in valores_n:
    print(f"\nArreglo de tamaño {n}x{n}:")
    print(crear_patron_a_cuadros(n))



Arreglo de tamaño 3x3:
[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [51]:
str1 = ['a','b','c', 'e','f','a','b','c']

dic = {}

for i in str1:
    if i not in dic.keys():
        dic[i] = 0
    dic[i] += 1
    
print(dic)


{'a': 2, 'b': 2, 'c': 2, 'e': 1, 'f': 1}


In [52]:
str1 = ['a','b','c', 'e','f','a','b','c']

dic = {}

for i in str1:
    dic.setdefault(i,0)
    dic[i] += 1
    
print(dic)


print(u)

{'a': 2, 'b': 2, 'c': 2, 'e': 1, 'f': 1}


In [67]:
dic = {'a': 1,'c': 2,'b': 3 }

dic.items()

for llave, valor in dic.items():
        print(f'{llave}: {valor}',end='\n')
        
dic.items()


a: 1
c: 2
b: 3


dict_items([('a', 1), ('c', 2), ('b', 3)])

In [72]:
persona_dic = {'Last Name': 'Doe', 'First Name': 'David', 'Company': 'Samsung'}

for dato, value in persona_dic.items():
    print(f'{dato}: {value}') 
    
    
persona_dic.items()

Last Name: Doe
First Name: David
Company: Samsung


dict_items([('Last Name', 'Doe'), ('First Name', 'David'), ('Company', 'Samsung')])

In [2]:
#Inventario en un dic
inventario = {"Café": 7, "Bolígrafo":3, "Vaso de papel": 2, 
         "Leche": 1, "Coca-Cola":4, "Libro":5}

#Funcion para comprobar si existe el item en el inventario
def comprobar(inventario,item_name): #recibe dic() e item_name que es una variable input
    if item_name in inventario.keys():# revisa si item_name existe en invenatario   
        return True
    else:
        return False
            
#funcion para agregar al inventario
def agregar(inventario): #recibe inventario
    if comprobar(inventario, item_name) == False: #comprube el return de comprobar()
        cantidad = int(input('ingresa la cantidad: '))#Si es no está en el dic pide al usuario que ingrese la cantidad y lo agrega al inventario
        inventario[item_name] = cantidad
        print(f'el item {item_name} fue agregado con éxito')
    else:  #si existe en el inventario imprime mensaje
        print(f'{item_name} ya está en el invetario')

#funcion para eliminar del inventario
def eliminar(inventario):
    if comprobar(inventario, item_name) == False: #Comprueba si existe 
        print('No tenemos disponible ese item') # si no existe imprime 
    else: #si existe entonces lo elimina
        del inventario[item_name]
        print(f'el item {item_name} fue eliminado con éxito')
        
    
while True:
    print('''
          1. Ver Stock
          2. Agregar item nuevo
          3. Borra item
          4. Salir
          ''')
    opcion = int(input('Ingresa el numero de la opción que deseas: '))
    
    if opcion == 1:
        for itemm, cantidadd in inventario.items():
            print(f'{itemm}: {cantidadd}')
    elif opcion == 2:
        item_name = input('Ingresa el nombre del item: ')
        agregar(inventario)
    elif opcion == 3:
        item_name = input('Ingresa el nombre del item a eliminar: ')
        eliminar(inventario)
    elif opcion == 4:
        print('Cerrando...')
        break



          1. Ver Stock
          2. Agregar item nuevo
          3. Borra item
          4. Salir
          
Café: 7
Bolígrafo: 3
Vaso de papel: 2
Leche: 1
Coca-Cola: 4
Libro: 5

          1. Ver Stock
          2. Agregar item nuevo
          3. Borra item
          4. Salir
          
el item Pasas fue agregado con éxito

          1. Ver Stock
          2. Agregar item nuevo
          3. Borra item
          4. Salir
          
Café: 7
Bolígrafo: 3
Vaso de papel: 2
Leche: 1
Coca-Cola: 4
Libro: 5
Pasas: 2

          1. Ver Stock
          2. Agregar item nuevo
          3. Borra item
          4. Salir
          
el item Pasas fue eliminado con éxito
{'Café': 7, 'Bolígrafo': 3, 'Vaso de papel': 2, 'Leche': 1, 'Coca-Cola': 4, 'Libro': 5}

          1. Ver Stock
          2. Agregar item nuevo
          3. Borra item
          4. Salir
          
Café: 7
Bolígrafo: 3
Vaso de papel: 2
Leche: 1
Coca-Cola: 4
Libro: 5

          1. Ver Stock
          2. Agregar item nuevo
          3. Bo